# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'app-swift-demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for app-swift-demo
  pod 'Firebase'

  target 'app-swift-demoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'app-swift-demoUITests' do
    # Pods for testing
  end

end

plugin 'cocoapods-art', :sources => [
  'slash-cocoapods-remote'
]

